### PR TITLE
Fe 13: As a user, I want to view which requirements are edited and want edits to be saved properly

### PR DESCRIPTION
**Pull request by rqualls**
- Changed so unmet conditions switch show the conditions which are checked instead of unchecked
- Saves data about changing the conditions in an array (there is some redundancy, but this is the best way to do it I think, we can talk about it if not)
- Implements reset conditions button
- shows when a condition is edited
- unit testing
Screenshot 2023-10-16 at 12 17 00 AM

### CODE REVIEW

**Review by AbdullahWins — COMMENTED** [review]
Good Job!

**Comment by rqualls** [comment]
> Good Job!

Hello? Are u a bot 🤔

**Comment by themnsavage** [comment]
I have no ideal who that guy is lol maybe its not good that our repos are public

**Comment by themnsavage** [comment]
okay i fixed it were random people can't just make comments on PRs

**Review by themnsavage — APPROVED** [review]
it looks good to be merge, but one thing that might be a little bit more user friendly(and less confusing). Is when you are on the edit page and don't make any edits and press continue the warning banner still shows up that edit changes will be saved. This showing of this warning even when no edits are made to infer that edits were made.

You don't have to change it though if you don't want to or see why too.

**Comment by rqualls** [comment]
> it looks good to be merge, but one thing that might be a little bit more user friendly(and less confusing). Is when you are on the edit page and don't make any edits and press continue the warning banner still shows up that edit changes will be saved. This showing of this warning even when no edits are made to infer that edits were made.
> 
> You don't have to change it though if you don't want to or see why too.

Yeah I considered that and I think that is a good change. I didn't add that bc I thought it would be difficult and I was lazy but now that I think abt it, it should not be hard to do. I'll add the change.

**Comment by rqualls** [comment]
@themnsavage A new commit does not overwrite a previous approval (a commit added after an approval is still approved)?  seems possibly risky. But I suppose for our purposes it doesn't matter too much

**Review by themnsavage — APPROVED** [review]

**Pull request merged**
